/**
 * Regenerates src/content/generated/index.ts from the problem modules on disk.
 * Each generated module `export default`s its problem; this aggregates them
 * into GENERATED_PROBLEMS, which src/content/index.ts merges into ALL_PROBLEMS.
 *
 * Run after generating or deleting problems:  npx tsx scripts/build-generated-index.ts
 */

import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { GENERATED_DIR } from "./lib/pipeline";
import { exportName } from "./lib/spec";

function main() {
  const slugs = readdirSync(GENERATED_DIR)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();

  const imports = slugs
    .map((slug) => `import ${exportName(slug)} from "./${slug}";`)
    .join("\n");
  const list = slugs.map((slug) => `  ${exportName(slug)},`).join("\n");

  const contents = `/**
 * AUTO-GENERATED by scripts/build-generated-index.ts — do not edit by hand.
 * Aggregates the AI-generated problem modules in this directory.
 */

import type { ProblemDef } from "../types";
${imports}

export const GENERATED_PROBLEMS: ProblemDef[] = [
${list}
];
`;

  writeFileSync(join(GENERATED_DIR, "index.ts"), contents);
  console.log(`Wrote generated index with ${slugs.length} problem(s).`);
}

main();
